{{- if eq (include "erpnext.redisCacheHost" .) ""}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "erpnext.fullname" . }}-redis-cache
  labels:
    {{- include "erpnext.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "erpnext.name" . }}-redis-cache
      app.kubernetes.io/instance: {{ .Release.Name }}-redis-cache
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "erpnext.name" . }}-redis-cache
        app.kubernetes.io/instance: {{ .Release.Name }}-redis-cache
    spec:
      serviceAccountName: {{ include "erpnext.serviceAccountName" . }}-redis
      containers:
      - name: master
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        command: ["redis-server"]
        args:
          - "--bind 0.0.0.0"
          - "--maxmemory 292mb"
          - "--maxmemory-policy allkeys-lru"
          - "--appendonly no"
          - "--save \"\""
        resources: {}
        {{- if .Values.redis.extraEnv }}
        env:
          {{- if .Values.redis.extraEnv }}
          {{- toYaml .Values.redis.extraEnv | nindent 12 }}
          {{- end }}
        {{- end }}
        ports:
        - containerPort: 6379
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 10
{{- end }}